baseURL: 'http://blog.htchz.cc/'
languageCode: zh-CN
title: 土川的自留地
theme: hugo-PaperMod

permalinks:
  post: '/posts/:slug'
  name: 首页
  url: /
  weight: '1'

menu:
  main:
    - name: POSTS
      url: /posts
      weight: '2'
    - name: ABOUT
      url: /about
      weight: '4'
    - name: SEARCH
      url: /search
      weight: '5'

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

params:
  homeInfoParams:
    Title: 土川的自留地
    Content: Be positive, stay patient.
  TocOpen: false
  ShowToc: true